To-Do: Interactive
danielochuba/To-Do-Structure pull request #4
Opened 2023-03-10 23:30 UTC by danielochuba

# To-Do: INTERACTIVE-LIST
- Allows the user to add a Todo task using the ADD Button.
- Remove a Task using the Trash icon.
- edit saved Task
- Clear all checked ✔️ item using the **Clear completed** Button

2023-03-10 23:44 UTC, VICTOR-CHUKWU requested changes
Hi @danielochuba  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 23:44 UTC, VICTOR-CHUKWU commented on modules/TaskHandle.js
> + * Updates the todos list with new items.
- [ ] kindly remove unused code from your code base

2023-03-10 23:44 UTC, VICTOR-CHUKWU commented on src/index.js
> +};
- [ ] [Optional] remove todo is not working you might want to check it out :+1:

2023-03-11 07:17 UTC, DammyShittu approved these changes
Hi @danielochuba,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-11 23:38 UTC, merged